/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateRouteImport } from './routes/create'
import { Route as TestRouteImport } from './routes/test'
import { Route as EditFacilityIdRouteImport } from './routes/edit/$facilityId'
import { Route as InfoFacilityIdRouteImport } from './routes/info/$facilityId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const EditFacilityIdRoute = EditFacilityIdRouteImport.update({
  id: '/edit/$facilityId',
  path: '/edit/$facilityId',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoFacilityIdRoute = InfoFacilityIdRouteImport.update({
  id: '/info/$facilityId',
  path: '/info/$facilityId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/test': typeof TestRoute
  '/edit/$facilityId': typeof EditFacilityIdRoute
  '/info/$facilityId': typeof InfoFacilityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/test': typeof TestRoute
  '/edit/$facilityId': typeof EditFacilityIdRoute
  '/info/$facilityId': typeof InfoFacilityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/test': typeof TestRoute
  '/edit/$facilityId': typeof EditFacilityIdRoute
  '/info/$facilityId': typeof InfoFacilityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/create' | '/test' | '/edit/$facilityId' | '/info/$facilityId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create' | '/test' | '/edit/$facilityId' | '/info/$facilityId'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/test'
    | '/edit/$facilityId'
    | '/info/$facilityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  TestRoute: typeof TestRoute
  EditFacilityIdRoute: typeof EditFacilityIdRoute
  InfoFacilityIdRoute: typeof InfoFacilityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$facilityId': {
      id: '/edit/$facilityId'
      path: '/edit/$facilityId'
      fullPath: '/edit/$facilityId'
      preLoaderRoute: typeof EditFacilityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/$facilityId': {
      id: '/info/$facilityId'
      path: '/info/$facilityId'
      fullPath: '/info/$facilityId'
      preLoaderRoute: typeof InfoFacilityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  TestRoute: TestRoute,
  EditFacilityIdRoute: EditFacilityIdRoute,
  InfoFacilityIdRoute: InfoFacilityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
