server:
  port: 8282

spring:
  application:
    name: fcase
  datasource:
    url: jdbc:sqlite:file:./data/app.db
    driver-class-name: org.sqlite.JDBC

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /docs
