CREATE TABLE IF NOT EXISTS Fish (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Organization (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Facility (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    location_type VARCHAR(20) NOT NULL,
    created TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS FacilityFish (
    facility_id BIGINT,
    fish_id BIGINT,

    PRIMARY KEY (facility_id, fish_id),

    CONSTRAINT fk_facility_fish
        FOREIGN KEY (facility_id)
        REFERENCES Facility(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_fish_facility
        FOREIGN KEY (fish_id)
        REFERENCES Fish(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FacilityOrgs (
    facility_id BIGINT,
    organization_id BIGINT,

    PRIMARY KEY (facility_id, organization_id),

    CONSTRAINT fk_facility_orgs
        FOREIGN KEY (facility_id)
        REFERENCES Facility(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_orgs_facility
        FOREIGN KEY (organization_id)
        REFERENCES Organization(id)
        ON DELETE CASCADE
);

INSERT INTO fish (name)
VALUES
    ('Laks'),
    ('Torsk'),
    ('Makrell'),
    ('Sild'),
    ('Sei');

INSERT INTO organization (name)
VALUES
    ('Nordic Havbruk AS'),
    ('Fjordlaks Organisasjon'),
    ('Norsk Oppdrettsforbund'),
    ('Havets Ressurser SA'),
    ('Blå Næring Norge'),
    ('Fjord & Fisk Oppdrett'),
    ('Nordhavet Akvakultur'),
    ('Kystens Oppdrettere'),
    ('Arctic Salmon Group'),
    ('Vestfjord Havbruk');

INSERT INTO facility (
    name,
    location_type,
    created
)
VALUES
    (
        'Oppdrett Bergen',
        'OCEAN',
        CURRENT_TIMESTAMP
    ),
    (
        'Oppdrett Stavanger',
        'OCEAN',
        CURRENT_TIMESTAMP
    ),
    (
        'Fiskefarm Oslo',
        'LAND',
        CURRENT_TIMESTAMP
    ),
    (
        'Forskningsstasjon Tromsø',
        'OCEAN',
        CURRENT_TIMESTAMP
    );

INSERT INTO FacilityFish (facility_id, fish_id)
VALUES
    (
        1,
        1 
    ),
    (
        1,
        2
    ),
    (
        1,
        3
    ),
    (
        2,
        3
    ),
    (
        3,
        1
    ),
    (
        3,
        4
    ),
    (
        4,
        5
    );


INSERT INTO FacilityOrgs (facility_id, organization_id)
VALUES
    (
        1,
        1
    ),
    (
        1,
        2 
    ),
    (
        2,
        5
    ),
    (
        2,
        7
    ),
    (
        3,
        4
    ),
    (
        3,
        5
    );
